version: '2'
services:
  elk:
    build:
      context: elk
      args:
        LOGSTASH_KEYS_DIR: ${LOGSTASH_KEYS_DIR}
    restart: always
    ports:
      - "5601:5601"
      - "9201:9200"
      - "5044:5044"
      - "5000:5000"
    environment:
      LOGSTASH_FILTER_POSTFIX_TIMESTAMP_TIMEZONE: ${LOGSTASH_FILTER_POSTFIX_TIMESTAMP_TIMEZONE}
    volumes:
      - ./elasticsearch/data:/var/lib/elasticsearch
  curator:
    build: curator
    restart: always
    environment:
      CURATOR_CLEAR_DAYS: ${CURATOR_CLEAR_DAYS}
  elastalert:
    build:
      context: elastalert
      args:
        setContainerTimezone: ${ELASTALERT_SET_CONTAINER_TIMEZONE}
        containerTimezone: ${ELASTALERT_CONTAINER_TIMEZONE}
    restart: always
    links:
      - elk:elasticsearch_host
    environment:
      SET_CONTAINER_TIMEZONE: ${ELASTALERT_SET_CONTAINER_TIMEZONE}
      CONTAINER_TIMEZONE: ${ELASTALERT_CONTAINER_TIMEZONE}
    volumes:
      - elastalert-config:/opt/config
      - elastalert-rules:/opt/rules
      - elastalert-logs:/opt/logs
volumes:
  elastalert-config:
    driver: local
  elastalert-rules:
    driver: local
  elastalert-logs:
    driver: local
